#!/usr/bin/env python
# -*- coding: utf -*-

from core import *
from modules import *

try:
    import argparse
    import sys
    from terminaltables import SingleTable

except:
    print """
Execution error:
  You required some basic Python libraries. 
  Please, check if you have all of them installed in your system or type 'pip install -r requirements.txt'.
"""
    sys.exit(-1)

#
# Constants
AUTHOR = "5h4d0wb0y"
VERSION = "1.0.0"
SOCIALS = [
    "facebook",
    "gmail",
    "hotmail",
    "instagram",
    "linkedin",
    "twitter",
    "vk",
    "yahoo"
]


class SocialBrute:

    def __init__(self):
        pass

    def show_banner(self):
        with open('banner', 'r') as f:
            data = f.read()
            print color.GREEN + data + color.ENDC
            print "\tAUTHOR:\t%s" % AUTHOR
            print "\tVERSION:\t%s" % VERSION
            print ""

    def validate_args(self):
        parser = argparse.ArgumentParser(description="")
        parser.add_argument("-u", "--username", metavar="<username>", dest="username",
                            default=None, help="Specify a username to crack")
        parser.add_argument("-s", "--social", metavar="<social>", dest="social",
                            default=None, help="Choose a social network between %s" % SOCIALS)
        parser.add_argument("-w", "--wordlist", metavar="<wordlist>", dest="wordlist",
                            default=None, help="Specify a wordlist path")
        parser.add_argument('-d', '--delay', type=int, default=1, dest='delay',
                            help='Provide the number of seconds the program delays as each password is tried')
        args = parser.parse_args()

        if not args.username:
            glob.print_error("Missing '-u' or '--username' argument!")
            sys.exit(-1)
        if not args.wordlist:
            glob.print_error("Missing '-w' or '--wordlist' argument!")
            sys.exit(-1)
        if not args.social:
            glob.print_error("Missing '-s' or '--social' argument!")
            sys.exit(-1)
        if args.social not in SOCIALS:
            data = []
            for x in SOCIALS:
                data.append("%s%s%s" % (color.PURPLE,x,color.ENDC))
            t = SingleTable([data], "%s%s Available Social Networks %s" % (color.YELLOW,color.BOLD,color.ENDC))
            print t.table
            print "\n"
            glob.print_error("Wrong '-s' or '--social' argument!")
            sys.exit(-1)
        return args

    def run(self, args):
        if args.social == 'facebook':
            a = facebook.Facebook(args.username, args.wordlist, args.delay)
        elif args.social == 'instagram':
            a = instagram.Instagram(args.username, args.wordlist, args.delay)
        elif args.social == 'twitter':
            a = twitter.Twitter(args.username, args.wordlist, args.delay)
        elif args.social == 'gmail':
            a = gmail.Gmail(args.username, args.wordlist, args.delay)
        elif args.social == 'hotmail':
            a = hotmail.Hotmail(args.username, args.wordlist, args.delay)
        elif args.social == 'linkedin':
            a = linkedin.LinkedIn(args.username, args.wordlist, args.delay)
        elif args.social == 'vk':
            a = vk.Vk(args.username, args.wordlist, args.delay)
        else:
            glob.print_error("This social is not supported!")
            sys.exit(-1)
        a.banner()
        a.crack()


# Main
if __name__ == "__main__":
    glob = globals.Globals()
    color = globals.Colors()
    socialbrute = SocialBrute()
    socialbrute.show_banner()
    args = socialbrute.validate_args()
    socialbrute.run(args)
